#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
wget https://www.w3.org/2002/06/flutejava-1.3.zip
unzip flutejava-1.3.zip -d /tmp
rm flutejava-1.3.zip
mkdir -p /disk1/java/maven-repo/com/innoventsolutions
mvn install:install-file \
  -Dfile="/tmp/flute-1.3/flute.jar" \
  -DgroupId="org.w3c" \
  -DartifactId="flute" \
  -Dversion="1.3" \
  -Dpackaging=jar \
  -DgeneratePom=true \
  -DlocalRepositoryPath=/disk1/java/maven-repo