#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
wget https://www.w3.org/2002/06/sacjava-1.3.zip
unzip sacjava-1.3.zip -d /tmp
rm sacjava-1.3.zip
mkdir -p /disk1/java/maven-repo/com/innoventsolutions
mvn install:install-file \
  -Dfile="/tmp/sac-1.3/sac.jar" \
  -DgroupId="org.w3c" \
  -DartifactId="sac" \
  -Dversion="1.3" \
  -Dpackaging=jar \
  -DgeneratePom=true \
  -DlocalRepositoryPath=/disk1/java/maven-repo